spring:
  application:
    name: Echo Room

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatapp}

server:
  port: ${PORT:8080}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}